import type { Metadata } from "next";

import "./globals.css";
import { CartProvider } from "./components/CartContext/CartContext";
import Header from "./components/Header/Header";
import { Raleway } from "next/font/google";

import Provider from "./provider";
import MobileMenu from "./components/MobileMenu/MobileMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway = Raleway({
  weight: ["500", "600"],
  subsets: ["cyrillic"],
  variable: "--font-raleway",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.variable}>
        <MobileMenu />
        <Provider>
          <CartProvider>
            <Header />

            <div className="container">{children}</div>
          </CartProvider>
        </Provider>
      </body>
    </html>
  );
}
